image: node:latest

stages:
- prepare
- validate
- release
- publish
- doc

prepare:
  stage: prepare
  script:
    - df -h

validate.swagger:
  stage: validate
  image: gkarthics/swagger-validate:0.2.0
  before_script:
    - swagger-cli -v
  script:
    - validate ./spec ./yaml

validate.redoc:
  stage: validate
  before_script:
    - npx -v
  script:
    - npx @redocly/openapi-cli lint ./spec/*.yaml

release:
  stage: release
  artifacts:
    untracked: true
  script:
    - tar -zcvf spec.tar.gz spec

publish:
  stage: publish
  dependencies:
    - release
  script:
    - ls -al
  artifacts:    
    paths:
      - spec.tar.gz
    expire_in: 30 days

pages:
  stage: doc
  script:
  - npm install -g redoc-cli
  - redoc-cli bundle -o public/index.html ./spec/*.yaml
  artifacts:
    paths:
    - public
  only:
  - master
