image: node:latest

stages:
- prepare
- validate
- doc
- publish

prepare.swagger:
  stage: prepare
  script:
    - df -h

validate.swagger:
  stage: validate
  image: gkarthics/swagger-validate:0.2.0
  before_script:
    - swagger-cli -v
  script:
    - validate . ./yaml

validate.openapi:
  stage: validate
  image: jamescooke/openapi-validator
  before_script:
    - openapi-validator --version
  script:
    - openapi-validator accountbalances.yaml
    - openapi-validator accounts.yaml

validate.redoc:
  stage: validate
  before_script:
    - npx -v
  script:
    - npx @redocly/openapi-cli lint *.yaml

publish:
  stage: publish
  script:
    - mkdir openapi
    - cp *.yml openapi
    - zip -r openapi.zip ./openapi
  artifacts:
    name: "viking-mill"
    paths:
      - ./site/openapi.zip
    expire_in: 30 days

pages:
  stage: doc
  script:
  - npm install -g redoc-cli
  - redoc-cli bundle -o public/index.html *.yaml
  artifacts:
    paths:
    - public
  only:
  - master
