image: node:latest

stages:
- prepare
- validate
- release
- publish
- doc

prepare:
  stage: prepare
  script:
    - df -h
  only:
  - master
  - develop

validate.swagger:
  stage: validate
  image: gkarthics/swagger-validate:0.2.0
  before_script:
    - swagger-cli -v
  script:
    - validate ./spec/openapi ./yaml
  only:
  - master
  - develop

validate.redoc:
  stage: validate
  before_script:
    - npx -v
  script:
    - npm run test
  only:
  - master
  - develop

release:
  stage: release
  artifacts:
    untracked: true
  script:
    - npm run build
    - tar -zcvf dist.tar.gz dist
  only:
  - master
  - develop

publish:
  stage: publish
  dependencies:
    - release
  script:
    - ls -al
  artifacts:
    paths:
      - dist.tar.gz
    expire_in: 30 days
  only:
  - master
  - develop

pages:
  stage: doc
  script:
  - npm install --save-dev redoc-cli
  - npm run redoc-blundle
  - cp ./docs/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - develop
